using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Jobly.SourceGenerator;

[Generator]
public sealed class JoblyMetadataGenerator : IIncrementalGenerator
{
    private const string IJobMetadataFullName = "Jobly.Core.Handlers.IJobMetadata";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var interfaceDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is InterfaceDeclarationSyntax,
                transform: static (ctx, ct) => ctx.SemanticModel.GetDeclaredSymbol(ctx.Node, ct) as INamedTypeSymbol)
            .Where(static symbol => symbol is not null);

        var compilationAndInterfaces = context.CompilationProvider.Combine(interfaceDeclarations.Collect());

        context.RegisterSourceOutput(compilationAndInterfaces, static (spc, source) => Execute(spc, source.Left, source.Right!));
    }

    private static void Execute(
        SourceProductionContext context,
        Compilation compilation,
        ImmutableArray<INamedTypeSymbol?> candidates)
    {
        var iJobMetadataSymbol = compilation.GetTypeByMetadataName(IJobMetadataFullName);
        if (iJobMetadataSymbol is null)
        {
            return;
        }

        foreach (var candidate in candidates)
        {
            if (candidate is null)
            {
                continue;
            }

            // Must directly extend IJobMetadata (not IJobMetadata itself)
            if (candidate.Equals(iJobMetadataSymbol, SymbolEqualityComparer.Default))
            {
                continue;
            }

            var extendsIJobMetadata = candidate.Interfaces.Any(i =>
                i.Equals(iJobMetadataSymbol, SymbolEqualityComparer.Default));

            if (!extendsIJobMetadata)
            {
                continue;
            }

            var properties = GetProperties(candidate);
            if (properties.Count == 0)
            {
                continue;
            }

            var ns = candidate.ContainingNamespace.IsGlobalNamespace
                ? null
                : candidate.ContainingNamespace.ToDisplayString();
            var interfaceName = candidate.Name;
            var implName = interfaceName.StartsWith("I", System.StringComparison.Ordinal)
                ? interfaceName.Substring(1) + "Impl"
                : interfaceName + "Impl";

            var source = GenerateImplementation(ns, interfaceName, implName, properties);
            var fileName = (ns != null ? ns + "." : string.Empty) + implName + ".g.cs";
            context.AddSource(fileName, source);
        }
    }

    private static readonly SymbolDisplayFormat NullableAwareFormat =
        SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(
            SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers
            | SymbolDisplayMiscellaneousOptions.UseSpecialTypes
            | SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    private static List<(string Name, string TypeFullName)> GetProperties(INamedTypeSymbol interfaceSymbol)
    {
        var properties = new List<(string Name, string TypeFullName)>();

        foreach (var member in interfaceSymbol.GetMembers())
        {
            if (member is IPropertySymbol prop && prop.GetMethod is not null && prop.SetMethod is not null)
            {
                var typeFullName = prop.Type.ToDisplayString(NullableAwareFormat);
                properties.Add((prop.Name, typeFullName));
            }
        }

        return properties;
    }

    private static string GenerateImplementation(
        string? ns,
        string interfaceName,
        string implName,
        List<(string Name, string TypeFullName)> properties)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (ns != null)
        {
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
        }

        // Emit the attribute on the interface as a partial interface
        sb.AppendLine($"    [global::Jobly.Core.Handlers.MetadataImplementation(typeof({implName}))]");
        sb.AppendLine($"    partial interface {interfaceName} {{ }}");
        sb.AppendLine();

        // Generate the implementation class
        sb.AppendLine($"    internal sealed class {implName} : global::System.Collections.Generic.Dictionary<string, object>, {(ns != null ? ns + "." : string.Empty)}{interfaceName}");
        sb.AppendLine("    {");
        sb.AppendLine($"        public {implName}() {{ }}");
        sb.AppendLine();
        sb.AppendLine($"        public {implName}(global::System.Collections.Generic.Dictionary<string, object> source)");
        sb.AppendLine("        {");
        sb.AppendLine("            foreach (var kvp in source)");
        sb.AppendLine("            {");
        sb.AppendLine("                this[kvp.Key] = kvp.Value;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");

        foreach (var (name, typeFullName) in properties)
        {
            sb.AppendLine();
            sb.AppendLine($"        public {typeFullName} {name}");
            sb.AppendLine("        {");
            sb.AppendLine($"            get => TryGetValue(\"{name}\", out var v) ? global::Jobly.Core.Handlers.MetadataConvert.To<{typeFullName}>(v)! : default!;");
            sb.AppendLine($"            set => this[\"{name}\"] = value!;");
            sb.AppendLine("        }");
        }

        sb.AppendLine("    }");

        if (ns != null)
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }
}
