using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Warp.Tests.SourceGenerator;

[Generator]
public sealed class DatabaseTestsGenerator : IIncrementalGenerator
{
    private const string AttributeSource = """
        namespace Warp.Tests;

        internal enum FixtureKind
        {
            Default = 0,
            Integration = 1,
            BatchedCompletion = 2,
            MultiServer = 3,
        }

        [System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
        internal sealed class GenerateDatabaseTestsAttribute : System.Attribute
        {
            public GenerateDatabaseTestsAttribute(FixtureKind kind = FixtureKind.Default)
            {
                Kind = kind;
            }

            public FixtureKind Kind { get; }
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("GenerateDatabaseTestsAttribute.g.cs", AttributeSource));

        var provider = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax { AttributeLists.Count: > 0 } c
                    && c.Modifiers.Any(m => string.Equals(m.ValueText, "abstract", System.StringComparison.Ordinal)),
                transform: static (ctx, _) => GetTargetOrNull(ctx))
            .Where(static x => x is not null)!
            .Collect();

        context.RegisterSourceOutput(provider, static (spc, targets) =>
        {
            foreach (var target in targets.Distinct())
            {
                Emit(spc, target!);
            }
        });
    }

    private static Target? GetTargetOrNull(GeneratorSyntaxContext ctx)
    {
        var classDecl = (ClassDeclarationSyntax)ctx.Node;
        var symbol = ctx.SemanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
        if (symbol is null)
        {
            return null;
        }

        var attr = symbol.GetAttributes().FirstOrDefault(a =>
            string.Equals(a.AttributeClass?.ToDisplayString(), "Warp.Tests.GenerateDatabaseTestsAttribute", System.StringComparison.Ordinal));
        if (attr is null)
        {
            return null;
        }

        var kind = FixtureKind.Default;
        if (attr.ConstructorArguments.Length > 0 && attr.ConstructorArguments[0].Value is int kindValue)
        {
            kind = (FixtureKind)kindValue;
        }

        return new Target(
            @namespace: symbol.ContainingNamespace.ToDisplayString(),
            baseName: symbol.Name,
            kind: kind);
    }

    private static void Emit(SourceProductionContext spc, Target target)
    {
        var (ns, baseName, kind) = target;

        // Strip the Base suffix if present — produces RetryTests_PostgreSql for RetryTestsBase.
        var concreteName = baseName.EndsWith("Base", System.StringComparison.Ordinal)
            ? baseName.Substring(0, baseName.Length - 4)
            : baseName;

        var (pgFixture, pgCollection, sqlFixture, sqlCollection) = kind switch
        {
            FixtureKind.Integration => ("PostgreSqlIntegrationFixture", "PostgreSqlIntegrationCollection", "SqlServerIntegrationFixture", "SqlServerIntegrationCollection"),
            FixtureKind.BatchedCompletion => ("PostgreSqlBatchedCompletionFixture", "PostgreSqlBatchedCompletionCollection", "SqlServerBatchedCompletionFixture", "SqlServerBatchedCompletionCollection"),
            FixtureKind.MultiServer => ("PostgreSqlMultiServerFixture", "PostgreSqlMultiServerCollection", "SqlServerMultiServerFixture", "SqlServerMultiServerCollection"),
            _ => ("PostgreSqlFixture", "PostgreSqlCollection", "SqlServerFixture", "SqlServerCollection"),
        };

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine($"[Xunit.Collection<global::Warp.Tests.Fixtures.{pgCollection}>]");
        sb.AppendLine("[Xunit.Trait(\"Category\", \"PostgreSql\")]");
        sb.AppendLine($"public sealed class {concreteName}_PostgreSql : {baseName}");
        sb.AppendLine("{");
        sb.AppendLine($"    public {concreteName}_PostgreSql(global::Warp.Tests.Fixtures.{pgFixture} fixture) : base(fixture) {{ }}");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine($"[Xunit.Collection<global::Warp.Tests.Fixtures.{sqlCollection}>]");
        sb.AppendLine("[Xunit.Trait(\"Category\", \"SqlServer\")]");
        sb.AppendLine($"public sealed class {concreteName}_SqlServer : {baseName}");
        sb.AppendLine("{");
        sb.AppendLine($"    public {concreteName}_SqlServer(global::Warp.Tests.Fixtures.{sqlFixture} fixture) : base(fixture) {{ }}");
        sb.AppendLine("}");

        spc.AddSource($"{ns.Replace('.', '_')}_{concreteName}.g.cs", sb.ToString());
    }

    private enum FixtureKind
    {
        Default = 0,
        Integration = 1,
        BatchedCompletion = 2,
        MultiServer = 3,
    }

    private sealed class Target(string @namespace, string baseName, FixtureKind kind)
    {
        public string Namespace { get; } = @namespace;

        public string BaseName { get; } = baseName;

        public FixtureKind Kind { get; } = kind;

        public override int GetHashCode() => (Namespace, BaseName, Kind).GetHashCode();

        public override bool Equals(object? obj) =>
            obj is Target other
            && string.Equals(Namespace, other.Namespace, System.StringComparison.Ordinal)
            && string.Equals(BaseName, other.BaseName, System.StringComparison.Ordinal)
            && Kind == other.Kind;

        public void Deconstruct(out string ns, out string bn, out FixtureKind k)
        {
            ns = Namespace;
            bn = BaseName;
            k = Kind;
        }
    }
}
