name: Build the Jobly Release

on:
  release:
    types: [published]

jobs:
  build:
    name: "Build and Publish Jobly"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0'
    
    - name: Add the GitHub NuGet Source
      run: |
        dotnet nuget add source "https://nuget.pkg.github.com/moberghr/index.json" --name github --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text

    # - name: Jobly - Run tests
    #   run: |
    #     cd src
    #     cd core
    #     cd Jobly.Tests
    #     dotnet restore
    #     dotnet build
    #     dotnet test

    - name: Jobly.Core - Install dependencies
      run: |
        cd src
        cd core
        cd Jobly.Core
        dotnet restore

    - name: "Jobly.Core - Create a NuGet package"
      run: dotnet pack -p:PackageVersion=${{github.ref_name}} --configuration Release

    - name: "Jobly.Core - Push NuGet package"
      run: dotnet nuget push "bin/Release/Jobly.Core.{{github.ref_name}}.nupkg" --source "github"

    - name: Jobly.UI - Install dependencies
      run: |
        cd ..
        cd Jobly.UI
        dotnet restore

    - name: "Jobly.UI - Create a NuGet package"
      run: dotnet pack -p:PackageVersion=${{github.ref_name}} --configuration Release

    - name: "Jobly.UI - Push NuGet package"
      run: dotnet nuget push "bin/Release/Jobly.UI.{{github.ref_name}}.nupkg" --source "github"

    - name: Jobly.Worker - Install dependencies
      run: |
        cd ..
        cd Jobly.Worker
        dotnet restore

    - name: "Jobly.Worker - Create a NuGet package"
      run: dotnet pack -p:PackageVersion=${{github.ref_name}} --configuration Release

    - name: "Jobly.Worker - Push NuGet package"
      run: dotnet nuget push "bin/Release/Jobly.Worker.{{github.ref_name}}.nupkg" --source "github"

    - name: "Cleanup - Remove NuGet Source"
      run: dotnet nuget remove source github